# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c810a95f5ec166535f0a211db726caa787b632118601b094af7e0c81083157587e9c260b4186cb0a1e057e35bdb72821fb48dae01e12d1f49b7b141eff9f2b1c

test:
  secret_key_base: 8275bc91ffbea91bca8d47d856e6281fc7ab92c6696ae66be490bc0aaa58cd793b0d6288c776ebea85c48333d123f3fa12b1abdbca45a02fda39d41eb820061f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
